// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: task-interface.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Implements struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Implements) Reset() {
	*x = Implements{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Implements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Implements) ProtoMessage() {}

func (x *Implements) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Implements.ProtoReflect.Descriptor instead.
func (*Implements) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{0}
}

type Prepare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Prepare) Reset() {
	*x = Prepare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare) ProtoMessage() {}

func (x *Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare.ProtoReflect.Descriptor instead.
func (*Prepare) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{1}
}

type Cancel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2}
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{3}
}

type Implements_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *Implements_Response) Reset() {
	*x = Implements_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Implements_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Implements_Response) ProtoMessage() {}

func (x *Implements_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Implements_Response.ProtoReflect.Descriptor instead.
func (*Implements_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Implements_Response) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type Implements_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Implements_Request) Reset() {
	*x = Implements_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Implements_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Implements_Request) ProtoMessage() {}

func (x *Implements_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Implements_Request.ProtoReflect.Descriptor instead.
func (*Implements_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{0, 1}
}

type Prepare_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GlobalConfig *Config `protobuf:"bytes,2,opt,name=global_config,json=globalConfig,proto3" json:"global_config,omitempty"`
}

func (x *Prepare_Request) Reset() {
	*x = Prepare_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prepare_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare_Request) ProtoMessage() {}

func (x *Prepare_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare_Request.ProtoReflect.Descriptor instead.
func (*Prepare_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Prepare_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prepare_Request) GetGlobalConfig() *Config {
	if x != nil {
		return x.GlobalConfig
	}
	return nil
}

type Prepare_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task_Ref `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *Prepare_Response) Reset() {
	*x = Prepare_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prepare_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare_Response) ProtoMessage() {}

func (x *Prepare_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare_Response.ProtoReflect.Descriptor instead.
func (*Prepare_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Prepare_Response) GetTask() *Task_Ref {
	if x != nil {
		return x.Task
	}
	return nil
}

type Cancel_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task_Ref `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *Cancel_Request) Reset() {
	*x = Cancel_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cancel_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel_Request) ProtoMessage() {}

func (x *Cancel_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel_Request.ProtoReflect.Descriptor instead.
func (*Cancel_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Cancel_Request) GetTask() *Task_Ref {
	if x != nil {
		return x.Task
	}
	return nil
}

type Cancel_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Cancel_Response) Reset() {
	*x = Cancel_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cancel_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel_Response) ProtoMessage() {}

func (x *Cancel_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel_Response.ProtoReflect.Descriptor instead.
func (*Cancel_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 1}
}

type Task_Ref struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StateId string `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
}

func (x *Task_Ref) Reset() {
	*x = Task_Ref{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Ref) ProtoMessage() {}

func (x *Task_Ref) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Ref.ProtoReflect.Descriptor instead.
func (*Task_Ref) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Task_Ref) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task_Ref) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

type Task_Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_Operation) Reset() {
	*x = Task_Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Operation) ProtoMessage() {}

func (x *Task_Operation) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Operation.ProtoReflect.Descriptor instead.
func (*Task_Operation) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{3, 1}
}

type Task_SubStage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_SubStage) Reset() {
	*x = Task_SubStage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_SubStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_SubStage) ProtoMessage() {}

func (x *Task_SubStage) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_SubStage.ProtoReflect.Descriptor instead.
func (*Task_SubStage) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{3, 2}
}

type Task_Operation_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task    *Task_Ref         `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Storage map[string]string `protobuf:"bytes,2,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Task_Operation_Request) Reset() {
	*x = Task_Operation_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Operation_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Operation_Request) ProtoMessage() {}

func (x *Task_Operation_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Operation_Request.ProtoReflect.Descriptor instead.
func (*Task_Operation_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{3, 1, 0}
}

func (x *Task_Operation_Request) GetTask() *Task_Ref {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *Task_Operation_Request) GetStorage() map[string]string {
	if x != nil {
		return x.Storage
	}
	return nil
}

type Task_Operation_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageUpdate map[string]string `protobuf:"bytes,2,rep,name=storage_update,json=storageUpdate,proto3" json:"storage_update,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Task_Operation_Response) Reset() {
	*x = Task_Operation_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Operation_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Operation_Response) ProtoMessage() {}

func (x *Task_Operation_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Operation_Response.ProtoReflect.Descriptor instead.
func (*Task_Operation_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{3, 1, 1}
}

func (x *Task_Operation_Response) GetStorageUpdate() map[string]string {
	if x != nil {
		return x.StorageUpdate
	}
	return nil
}

type Task_SubStage_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProvidedOrders []int32 `protobuf:"varint,1,rep,packed,name=provided_orders,json=providedOrders,proto3" json:"provided_orders,omitempty"`
}

func (x *Task_SubStage_Response) Reset() {
	*x = Task_SubStage_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_SubStage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_SubStage_Response) ProtoMessage() {}

func (x *Task_SubStage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_SubStage_Response.ProtoReflect.Descriptor instead.
func (*Task_SubStage_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{3, 2, 0}
}

func (x *Task_SubStage_Response) GetProvidedOrders() []int32 {
	if x != nil {
		return x.ProvidedOrders
	}
	return nil
}

type Task_SubStage_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *Task_Operation_Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	SubStage int32                   `protobuf:"varint,2,opt,name=sub_stage,json=subStage,proto3" json:"sub_stage,omitempty"`
}

func (x *Task_SubStage_Request) Reset() {
	*x = Task_SubStage_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_SubStage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_SubStage_Request) ProtoMessage() {}

func (x *Task_SubStage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_SubStage_Request.ProtoReflect.Descriptor instead.
func (*Task_SubStage_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{3, 2, 1}
}

func (x *Task_SubStage_Request) GetRequest() *Task_Operation_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Task_SubStage_Request) GetSubStage() int32 {
	if x != nil {
		return x.SubStage
	}
	return 0
}

var File_task_interface_proto protoreflect.FileDescriptor

var file_task_interface_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x1a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x39, 0x0a, 0x0a, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a,
	0x20, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x99, 0x01, 0x0a,
	0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x1a, 0x57, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x1a, 0x35, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a,
	0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x7a, 0x78,
	0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52,
	0x65, 0x66, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x4a, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x1a, 0x34, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a,
	0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x7a, 0x78,
	0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52,
	0x65, 0x66, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0xe1, 0x04, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x34, 0x0a,
	0x03, 0x52, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x1a, 0xf9, 0x02, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0xbc, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a,
	0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x7a, 0x78,
	0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52,
	0x65, 0x66, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x4a, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x7a, 0x78, 0x70, 0x6d,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x1a, 0x3a, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0xac, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a,
	0x0e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x40, 0x0a,
	0x12, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0xa6, 0x01, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x67, 0x65, 0x1a, 0x33, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x64, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x1a, 0x65, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x75, 0x62, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x73, 0x75, 0x62, 0x53, 0x74, 0x61, 0x67, 0x65, 0x32, 0xa8, 0x07, 0x0a, 0x0d, 0x54, 0x61, 0x73,
	0x6b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x0a, 0x49, 0x6d,
	0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x7a, 0x78, 0x70, 0x6d,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a,
	0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x1c, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x12, 0x1b, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b,
	0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x23,
	0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0c, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x15, 0x2e, 0x7a, 0x78,
	0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52,
	0x65, 0x66, 0x1a, 0x23, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0c, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x22, 0x2e, 0x7a, 0x78, 0x70, 0x6d,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x53, 0x75, 0x62,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x52, 0x75, 0x6e, 0x12, 0x15, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52, 0x65, 0x66, 0x1a, 0x23, 0x2e, 0x7a, 0x78, 0x70,
	0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x53, 0x75,
	0x62, 0x53, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x59, 0x0a, 0x0a, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x12,
	0x23, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x2e, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x24, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0a,
	0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x15, 0x2e, 0x7a, 0x78, 0x70,
	0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52, 0x65,
	0x66, 0x1a, 0x23, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x2e, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0a, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x22, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x7a, 0x78, 0x70,
	0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5f, 0x0a, 0x10, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x2e, 0x7a, 0x78, 0x70, 0x6d, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x7a, 0x78,
	0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_interface_proto_rawDescOnce sync.Once
	file_task_interface_proto_rawDescData = file_task_interface_proto_rawDesc
)

func file_task_interface_proto_rawDescGZIP() []byte {
	file_task_interface_proto_rawDescOnce.Do(func() {
		file_task_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_interface_proto_rawDescData)
	})
	return file_task_interface_proto_rawDescData
}

var file_task_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_task_interface_proto_goTypes = []interface{}{
	(*Implements)(nil),              // 0: zxpm.plugin.Implements
	(*Prepare)(nil),                 // 1: zxpm.plugin.Prepare
	(*Cancel)(nil),                  // 2: zxpm.plugin.Cancel
	(*Task)(nil),                    // 3: zxpm.plugin.Task
	(*Implements_Response)(nil),     // 4: zxpm.plugin.Implements.Response
	(*Implements_Request)(nil),      // 5: zxpm.plugin.Implements.Request
	(*Prepare_Request)(nil),         // 6: zxpm.plugin.Prepare.Request
	(*Prepare_Response)(nil),        // 7: zxpm.plugin.Prepare.Response
	(*Cancel_Request)(nil),          // 8: zxpm.plugin.Cancel.Request
	(*Cancel_Response)(nil),         // 9: zxpm.plugin.Cancel.Response
	(*Task_Ref)(nil),                // 10: zxpm.plugin.Task.Ref
	(*Task_Operation)(nil),          // 11: zxpm.plugin.Task.Operation
	(*Task_SubStage)(nil),           // 12: zxpm.plugin.Task.SubStage
	(*Task_Operation_Request)(nil),  // 13: zxpm.plugin.Task.Operation.Request
	(*Task_Operation_Response)(nil), // 14: zxpm.plugin.Task.Operation.Response
	nil,                             // 15: zxpm.plugin.Task.Operation.Request.StorageEntry
	nil,                             // 16: zxpm.plugin.Task.Operation.Response.StorageUpdateEntry
	(*Task_SubStage_Response)(nil),  // 17: zxpm.plugin.Task.SubStage.Response
	(*Task_SubStage_Request)(nil),   // 18: zxpm.plugin.Task.SubStage.Request
	(*Config)(nil),                  // 19: zxpm.plugin.Config
}
var file_task_interface_proto_depIdxs = []int32{
	19, // 0: zxpm.plugin.Prepare.Request.global_config:type_name -> zxpm.plugin.Config
	10, // 1: zxpm.plugin.Prepare.Response.task:type_name -> zxpm.plugin.Task.Ref
	10, // 2: zxpm.plugin.Cancel.Request.task:type_name -> zxpm.plugin.Task.Ref
	10, // 3: zxpm.plugin.Task.Operation.Request.task:type_name -> zxpm.plugin.Task.Ref
	15, // 4: zxpm.plugin.Task.Operation.Request.storage:type_name -> zxpm.plugin.Task.Operation.Request.StorageEntry
	16, // 5: zxpm.plugin.Task.Operation.Response.storage_update:type_name -> zxpm.plugin.Task.Operation.Response.StorageUpdateEntry
	13, // 6: zxpm.plugin.Task.SubStage.Request.request:type_name -> zxpm.plugin.Task.Operation.Request
	5,  // 7: zxpm.plugin.TaskExecution.Implements:input_type -> zxpm.plugin.Implements.Request
	6,  // 8: zxpm.plugin.TaskExecution.Prepare:input_type -> zxpm.plugin.Prepare.Request
	8,  // 9: zxpm.plugin.TaskExecution.Cancel:input_type -> zxpm.plugin.Cancel.Request
	13, // 10: zxpm.plugin.TaskExecution.ExecuteCheck:input_type -> zxpm.plugin.Task.Operation.Request
	10, // 11: zxpm.plugin.TaskExecution.PrepareBegin:input_type -> zxpm.plugin.Task.Ref
	18, // 12: zxpm.plugin.TaskExecution.ExecuteBegin:input_type -> zxpm.plugin.Task.SubStage.Request
	10, // 13: zxpm.plugin.TaskExecution.PrepareRun:input_type -> zxpm.plugin.Task.Ref
	17, // 14: zxpm.plugin.TaskExecution.ExecuteRun:input_type -> zxpm.plugin.Task.SubStage.Response
	10, // 15: zxpm.plugin.TaskExecution.PrepareEnd:input_type -> zxpm.plugin.Task.Ref
	18, // 16: zxpm.plugin.TaskExecution.ExecuteEnd:input_type -> zxpm.plugin.Task.SubStage.Request
	13, // 17: zxpm.plugin.TaskExecution.ExecuteFinishing:input_type -> zxpm.plugin.Task.Operation.Request
	4,  // 18: zxpm.plugin.TaskExecution.Implements:output_type -> zxpm.plugin.Implements.Response
	7,  // 19: zxpm.plugin.TaskExecution.Prepare:output_type -> zxpm.plugin.Prepare.Response
	9,  // 20: zxpm.plugin.TaskExecution.Cancel:output_type -> zxpm.plugin.Cancel.Response
	14, // 21: zxpm.plugin.TaskExecution.ExecuteCheck:output_type -> zxpm.plugin.Task.Operation.Response
	17, // 22: zxpm.plugin.TaskExecution.PrepareBegin:output_type -> zxpm.plugin.Task.SubStage.Response
	14, // 23: zxpm.plugin.TaskExecution.ExecuteBegin:output_type -> zxpm.plugin.Task.Operation.Response
	17, // 24: zxpm.plugin.TaskExecution.PrepareRun:output_type -> zxpm.plugin.Task.SubStage.Response
	14, // 25: zxpm.plugin.TaskExecution.ExecuteRun:output_type -> zxpm.plugin.Task.Operation.Response
	17, // 26: zxpm.plugin.TaskExecution.PrepareEnd:output_type -> zxpm.plugin.Task.SubStage.Response
	14, // 27: zxpm.plugin.TaskExecution.ExecuteEnd:output_type -> zxpm.plugin.Task.Operation.Response
	14, // 28: zxpm.plugin.TaskExecution.ExecuteFinishing:output_type -> zxpm.plugin.Task.Operation.Response
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_task_interface_proto_init() }
func file_task_interface_proto_init() {
	if File_task_interface_proto != nil {
		return
	}
	file_config_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_task_interface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Implements); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prepare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cancel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Implements_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Implements_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prepare_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prepare_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cancel_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cancel_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Ref); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_SubStage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Operation_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Operation_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_SubStage_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_SubStage_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_interface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_interface_proto_goTypes,
		DependencyIndexes: file_task_interface_proto_depIdxs,
		MessageInfos:      file_task_interface_proto_msgTypes,
	}.Build()
	File_task_interface_proto = out.File
	file_task_interface_proto_rawDesc = nil
	file_task_interface_proto_goTypes = nil
	file_task_interface_proto_depIdxs = nil
}
